AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'examples/*'
    - 'vendor/**/*'
    - 'spec/**/*'

Style/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Style/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
